### ISSUE TITLE
There is no [permission] with id  新建permission。static 不更新

### ISSUE THREAD

**Issue by Johnzero** [hyperf-cms/hyperf-api#2]
{"code":500,"msg":"服务器错误 There is no [permission] with id `82`.:: FILE:\/Users\/wangsong\/Desktop\/skeleton\/api\/vendor\/donjan-deng\/hyperf-permission\/src\/Exceptions\/PermissionDoesNotExist.php:: LINE: 18","data":[]}

**Comment by linyiyuan** [comment]
是怎么样触发了这个报错的

**Comment by linyiyuan** [comment]
应该是权限缓存了，在redis删除一下看看
