### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Johnzero** [hyperf-cms/hyperf-api#3]
loginservice 206：
             
   foreach ($value['children'] as $k => $v) {
                    $temp = [];
                    $routers[$value['id']]['children'][] = [
                        'name'       => $v['name'],
                        'path'       => $v['url'],
                        'hidden'     => $v['hidden'],
                        'alwaysShow' => true,
                        'component'  => $v['component'],
                        'meta'       => [
                            'icon'  => $v['icon'],
                            'title' => $v['display_name'],
                        ],
                    ];

**Comment by Johnzero** [comment]
超过3级目录节点无法添加，后续补充。

**Comment by linyiyuan** [comment]
已经修复
