### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by kphcdr** [hyperf-cms/hyperf-api#5]
swoole  Version => 4.8.6
php  PHP 7.4.27 
其他的hyperf 的项目是可以正常运行的，但是这个项目运行php bin/hyperf.php 没有任何返回

<img width="333" alt="image" src="https://user-images.githubusercontent.com/3817838/153582582-b53f55b4-71d9-425d-962a-b7073679fe21.png">

**Comment by linyiyuan** [comment]
php watch看下，不应该的，起码会返回错误啥的，你看下错误日志

**Comment by kphcdr** [comment]
![image](https://user-images.githubusercontent.com/3817838/154005048-21757dde-9b1e-4eb7-a086-c717436616c4.png)
看上去是版本兼容有问题
